version: '2'
services: 
    web:
        build: .
        working_dir: /var/www/html
        volumes: 
        - ./:/var/www/html
        ports:
        - 93:80
        env_file:
        - .env
        depends_on: 
        - db
    db:
        image: mariadb
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: app
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        ports:
            - 3306